### ISSUE TITLE
EMA: RefreshMsgImpl.toString fails with AssertionError

### ISSUE THREAD

**Issue by FrankConstructor** [Refinitiv/Real-Time-SDK#144]
Hello,

I encounter an error - see stacktrace below:
```java
java.lang.AssertionError
at com.thomsonreuters.upa.codec.MsgImpl.checkPrivateStream(MsgImpl.java:1333) [upa.jar:etaj3.2.1.L1.all.rrg]
at com.thomsonreuters.ema.access.RefreshMsgImpl.privateStream(RefreshMsgImpl.java:181) [ema.jar:emaj3.2.1.L1.all.rrg]
at com.thomsonreuters.ema.access.RefreshMsgImpl.toString(RefreshMsgImpl.java:419) [ema.jar:emaj3.2.1.L1.all.rrg]
at com.thomsonreuters.ema.access.RefreshMsgImpl.toString(RefreshMsgImpl.java:396) [ema.jar:emaj3.2.1.L1.all.rrg]
```

Neither the RefreshMsg (fluent) privateStream getter's nor the MsgImpl.checkPrivateStream( method's javadoc have any notion that such can happen.

This has some bad impacts such as that logging fails etc.

**Comment by APaias** [comment]
Hi @FrankConstructor ,
We need more information to proceed further, here are some questions for you:
- Could you describe the use case in which this error occurs?
- Could you describe how the RefreshMsg is obtained?
- If it is possible could you provide full stack trace with all method calls that belong to Elektron SDK?

**Comment by vlevendel** [comment]
@FrankConstructor any feedback?
