### ISSUE TITLE
JSON Converter unexpected value: Invalid date value: 2022-11

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [Refinitiv/Real-Time-SDK#207]
The client reported this issue on https://community.developers.refinitiv.com/questions/97248/exception-typeommjsonconverterexception-textfailed.html. 

I can replicate this issue with EMA Java 3.6.6.L1 with the websocket connection. 

Run the consumer application via the websocket connection and subscribe to ALINN.PA. 

EMA will report this exception.

```
[{"ID":3,"Type":"Refresh","Key":{"Service":"ELEKTRON_DD","Name":"ALINN.PA"},"State":{"Stream":"Open","Data":"Ok","Text":"*All is well"},"Qos":{"Timeliness":"Realtime","Rate":"TickByTick"},"PermData":"AxHygTLA","SeqNumber":4768,"Fields":{"PROD_PERM":8132,"RDNDISPLAY":116,"DSPLY_NAME":"INNELEC MULTIMED","RDN_EXCHID":"PAR","TIMACT":"00:00:00","TRDPRC_1":null,"TRDPRC_2":null,"TRDPRC_3":null,"TRDPRC_4":null,"TRDPRC_5":null,"NETCHNG_1":null,"HIGH_1":null,"LOW_1":null,"PRCTCK_1":null,"CURRENCY":"EUR","TRADE_DATE":"2022-08-30","TRDTIM_1":null,"OPEN_PRC":null,"HST_CLOSE":5.1800,"BID":5.1000,"ASK":5.1800,"NEWS":"    ","NEWS_TIME":null,"BIDSIZE":103,"ASKSIZE":33,"ACVOL_1":null,"EARNINGS":0.3861,"YIELD":3.861,"PERATIO":13.4162,"DIVPAYDATE":"2022-11","EXDIVDATE":"2022-09-27","BLKCOUNT":null,"TRD_UNITS":"4DP ",}"}}', ErrorCode='-1', SessionInfo='hostname: 192.168.27.94
	IP address: null
	port: 15000
	connected component info: unavailable
	channel state: active
	connection type: webSocket
	protocol type: Rssl JSON format
	major version: 14
	minor version: 1
	ping timeout: 30
	max fragmentation size: 0
	max output buffers: 0
	guaranteed output buffers: 0
	number input buffers: 0
	system send buffer size: 0
	system receive buffer size: 0
	compression type: none
	compression threshold: 0'
	at com.refinitiv.ema.access.OmmBaseImpl.ommJCExcept(OmmBaseImpl.java:1669)
	at com.refinitiv.ema.access.OmmConsumerImpl.handleJsonConverterError(OmmConsumerImpl.java:653)
	at com.refinitiv.ema.access.OmmBaseImpl.reactorJsonConversionEventCallback(OmmBaseImpl.java:327)
	at com.refinitiv.eta.valueadd.reactor.Reactor.performChannelRead(Reactor.java:3507)
	at com.refinitiv.eta.valueadd.reactor.Reactor.dispatchChannel(Reactor.java:2737)
	at com.refinitiv.eta.valueadd.reactor.ReactorChannel.dispatch(ReactorChannel.java:612)
	at com.refinitiv.ema.access.OmmBaseImpl.rsslReactorDispatchLoop(OmmBaseImpl.java:1561)
	at com.refinitiv.ema.access.OmmBaseImpl.run(OmmBaseImpl.java:1703)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The problem is that the field DIVPAYDATE contains "2022-11" and EMA is unable to convert it. 
```
"DIVPAYDATE":"2022-11"
```

**Comment by L-Karchevska** [comment]
@jirapongse-refinitiv Thank you for bringing up this issue, we will investigate it and fix it in the upcoming releases.

**Comment by marcgastineau** [comment]
@L-Karchevska after this exception, no more subscription works and no updates are received.
Moreover, I managed to have the same exception on AMT_OS on other instrument

**Comment by L-Karchevska** [comment]
@marcgastineau Thank you for the details! We reproduced the issue and are working on it.

**Comment by vlevendel** [comment]
Fix available with tag Real-Time-SDK-2.0.7.L1.

**Comment by farnulfo** [comment]
> Fix available with tag Real-Time-SDK-2.0.7.L1.

Any ETA for the maven release ?

**Comment by vlevendel** [comment]
@farnulfo Apologies for the delay.

The release is available on Maven today but still not appearing in search. 
![image](https://user-images.githubusercontent.com/13593674/195905907-540c348b-25cf-468b-b7c9-4340797d45a4.png)

**Comment by farnulfo** [comment]
It's ok today : https://mvnrepository.com/artifact/com.refinitiv.ema/ema/3.6.7.0
Thanks
