### ISSUE TITLE
Misaligned EmaString objects in `onInvalidUsage` (C++)

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#219]
I run with the various undefined behaviour and memory sanitizers enabled. While debugging a configuration issue, my `OmmConsumerErrorClient::onInvalidUsage` was called with an `EmaString` that wasn't on an 8-byte alignment (which is required by the type):

```
runtime error: member access within misaligned address 0x62100001558c for type 'const struct EmaString', which requires 8 byte alignment
0x62100001558c: note: pointer points here
  2a 00 00 00 d0 94 a2 f4  ff 7f 00 00 b4 55 01 00  10 62 00 00 2a 00 00 00  00 00 00 00 00 00 00 00
              ^ 
pc_0x555555dd5b7f###func_onInvalidUsage###file_ELIDED###line_275###obj_(xxx+0x881b7f)
```

`gdb` confirms this is the case:

```
(gdb) p &text
$1 = (const refinitiv::ema::access::EmaStringInt *) 0x62100001558c
(gdb) p text
$2 = (const refinitiv::ema::access::EmaStringInt &) @0x62100001558c: {<refinitiv::ema::access::EmaString> = {_vptr.EmaString = 0x7ffff4a294d0 <vtable for refinitiv::ema::access::EmaStringInt+16>, static npos = 4294967295, _pString = 0x6210000155b4 "Unknown connection type. Passed in type is", _length = 42, _capacity = 0}, _pTempString = 0x0, _nullTerminated = true}
```

`0x62100001558c` is not on an 8-byte boundary, and `EmaString` (of which `EmaStringInt` is a subclass) needs to be (as it has a `vtable` within it that requires pointer-sized alignment, which on 64-bit systems is 8-bytes).

Here's the stacktrace that passed in the misaligned message:

```
#1  0x00007ffff4922bd4 in refinitiv::ema::access::OmmBaseImpl::notifErrorClientHandler (ommException=..., errorClient=...) at /tmp/tmp.4uZyTdl4w4/refinitiv-rtsdk_1667424860637/work/Cpp-C/Ema/Src/Access/Impl/OmmBaseImpl.cpp:3408
#2  0x00007ffff47cca73 in refinitiv::ema::access::OmmBaseImpl::initialize (this=this@entry=0x620000000080, configImpl=<optimized out>) at /tmp/tmp.4uZyTdl4w4/refinitiv-rtsdk_1667424860637/work/Cpp-C/Ema/Src/Access/Impl/OmmBaseImpl.cpp:2413
#3  0x00007ffff49363b2 in refinitiv::ema::access::OmmConsumerImpl::OmmConsumerImpl (this=this@entry=0x620000000080, config=..., adminClient=..., errorClient=..., adminClosure=adminClosure@entry=0x0) at /tmp/tmp.4uZyTdl4w4/refinitiv-rtsdk_1667424860637/work/Cpp-C/Ema/Src/Access/Impl/OmmConsumerImpl.cpp:69
#4  0x00007ffff493195d in refinitiv::ema::access::OmmConsumer::OmmConsumer (this=0x7fffffffda40, config=..., adminClient=..., errorClient=..., closure=0x0) at /tmp/tmp.4uZyTdl4w4/refinitiv-rtsdk_1667424860637/work/Cpp-C/Ema/Src/Access/Impl/OmmConsumer.cpp:106
```

The text appears to come from the `OmmException` which has a `reinterpret_cast`ed `_space` buffer which does not have the required alignment for an `EmaStringInt`.

I believe a change like:

```diff
-mutable char				_space[MAX_SIZE_PLUS_PADDING];
+alignas(alignof(EmaStringInt)) mutable char _space[MAX_SIZE_PLUS_PADDING];
```

See e.g. https://godbolt.org/z/se74brWzf and for an example where the sanitizer trips up with mostly equivalent code to rtsdk: https://godbolt.org/z/K6jjWPnrv

**Comment by ViktorYelizarov** [comment]
@mattgodbolt
Thank you for reporting this issue, we've created an internal JIRA for it and started the investigation.
